# @name Hello
GET http://localhost:3333

###

# @name Prompts
GET http://localhost:3333/prompts

###

# @name TopicSelection
GET http://localhost:3333/selection-topic

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
   "selections": ["Pontos turisticos"],                                             
   "localization": "Espirito Santo",
   "startDate": "13/09/2023",
   "endDate": "14/09/2023",
   "temperature": 0.5,
   "prompt": "Seu papel é gerar uma roteiro breve e sem muitos detalhes de viagem para {localization} do dia {startDate} até o dia {endDate}, com os seguintes pontos importantes: {selections}"
}